---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pycont-operator
  name: pycont-operator
  namespace: pycont
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pycont-operator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pycont-operator
    spec:
      serviceAccountName: pycont-operator
      containers:
      - image: prgcont/pycont-operator
        name: pycont-operator
        imagePullPolicy: Always
        env:
          - name: CURRENT_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace

          - name: CURRENT_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: PYTHONUNBUFFERED
            value: "0"
