---
apiVersion: v1
kind: Namespace
metadata:
  name: pycont

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pycont-operator
  namespace: pycont

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-admin
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pycont-operator
  namespace: pycont
subjects:
- kind: ServiceAccount
  name: pycont-operator
  namespace: ergon
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
